### ISSUE TITLE
PSTATE var needed

### ISSUE THREAD

**Issue by alinasmahl1** [Drexel-UHC/hcup-etl#27]
can we add PSTATE - example: if w're lookign at the NY 2017 SID

and someone was living in jersey, but hopsitalized in NY- PSTATEE would be = NJ
so we want PSTATE in addition to SID state
becuase we don't actually want to include people who lived in jersey in some of these analysis

**Comment by ran-codes** [comment]
pending production run on UB computer

- [ ] ETL and DBT update. 
- [ ] prodrun on UB comp

**Comment by ran-codes** [comment]
@her43 production run done. Feel free to close issue after you've checked over the results.

**Comment by ran-codes** [comment]
stale. and resolved. please reopen if still an issue. Thanks!
