### ISSUE TITLE
Package setup

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-etl#28]
In prep for transition. To document functions and deploy package.

## Action Items

- [x] init package at root with `usethis::create_package("drexel.uhc.hcup.etl")
- [x] `renv::init()`
- [x] install 'devtools' 
- [x] check Rstudio is connected to GitHub `usethis::git_sitrep()`. If not then set up with use_git_config(), create_github_token() and gitcreds_set()
- [ ]

**Comment by ran-codes** [comment]
@her43 do you have an orcid? I want to set up the package so both of us are authors and want to make sure you get credit.

**Comment by her43** [comment]
> @her43 do you have an orcid? I want to set up the package so both of us are authors and want to make sure you get credit.

Yup! 0000-0001-7947-6850 [https://orcid.org/0000-0001-7947-6850](https://orcid.org/0000-0001-7947-6850)

**Comment by ran-codes** [comment]
closing for now. will reconsider packaging this later if a priority.
