### ISSUE TITLE
ETL New York data Sep 2023

### ISSUE THREAD

**Issue by ran-codes** [Drexel-UHC/hcup-etl#31]
Issue to document how to laod new data into DBT. New data was uploaded into  `\\files.drexel.edu\encrypted\SOPH\UHC\SchnakeMahl_HCUP\raw\_upload_2023-09-11

## Action Items

- [x] pre-req
    - [x] work on a UHC workstation
    - [x] Have SAS installed
    - [x] Have Stata installed
- [x] Load data into DBT source see comment below for details/protocol
'

By now the data is in /dbt source folder and we can move onto  DBT modeling in other repo: https://github.com/Drexel-UHC/hcup-dbt

**Comment by ran-codes** [comment]
# Load data into DBT source

### 1. Load data into DBT Source

- [x] cleaned up /raw. 
    - [x] moved do_files folder out to  local repo folder (/documents/load-programs/stataload_ip)  Note that this /raw folder is only for raw data (.acs files).
    - [x] moved new formatted data to /to-process folder. (pipeline is not set up for these current and we will deal with them later in #30)

#### Step 1: Evaluate ETL status
```r
## Get status of /raw folder
df_status = get_etl_status(etl)

## Subset what we need to do for new york. 
df_todo = df_status  |> 
  filter(str_detect(dataset_id, 'NY_'))  %>% 
  filter(is.na(codebook))
```

#### Step 2: Copy load programs

- [ ]  `copy_load_program(etl)`

note that this scans the load files in the rpeo and inserts the appropriate laod file; prioritizing the .Do if available. 

#### Step 3: Run load programs 

Note that .Do files are easy just click but Sas files need to add a proc export. 

- [ ] NY_SIDC_2012_CORE (SAS)
    - [ ] open file and add aprrproaite SAS expert code (see `Appendex Code 1` to end 
    - [ ] submit all
- [ ] NY_SIDC_2020_CORE (Stata)
   - [ ] open .Do file and Tools>Execute (do)

```sas
### Appendex Code 1
PROC EXPORT DATA=NY_SIDC_2012_CORE
            OUTFILE='NY_SID_2012_CORE'
            DBMS=STATA REPLACE;
RUN;    
```

### Step 4: Load as parquet 

- [ ] `load_dta_to_db(etl)`

This takes a while just let if run in the background on a UHC high RAM workstation. Note that I already did this in prep so  for NY_SID_2020_CORE, and NY_SID_2012_CORE so we can focus on the process during meeting.  

```
→ Start .dta to parquet conversion for NY_SID_2020_CORE
✔ Finished .dta to parquet conversion for NY_SID_2020_CORE
→ Start .dta to parquet conversion for NY_SID_2012_CORE
✔ Finished .dta to parquet conversion for NY_SID_2012_CORE
```
### Step 5: Operationalize codebook

```r
>     generate_codebooks(etl)    
Joining with `by = join_by(dataset_id)`
→ Start codebook generation for NY_SID_2020_CORE
✔ Codebook written for NY_SID_2020_CORE
→ Start codebook generation for NY_SID_2012_CORE
✔ Codebook written for NY_SID_2012_CORE
✔ 2 codebooks written
Joining with `by = join_by(var)`
✔ Compiled codebooks at clean/df_codebooks.csv
Joining with `by = join_by(dataset_id)`
`

**Comment by her43** [comment]
>  Step 3: Run load programs

NY 2012:
- [ ] CHGS
- [ ] CORE
- [ ] DX_PR_GRPS
- [ ] SEVERITY

NY 2013:
- [ ] CHGS
- [ ] CORE
- [ ] DX_PR_GRPS
- [ ] SEVERITY

NY 2014:
- [ ] CHGS
- [ ] CORE
- [ ] DX_PR_GRPS
- [ ] SEVERITY

NY 2015:
- [ ] CHGS
- [ ] CORE
- [ ] DX_PR_GRPS
- [ ] SEVERITY

NY 2016:
- [ ] CHGS
- [ ] CORE

NY 2020:
- [ ] CHGS
- [ ] CORE
- [ ] DX_PR_GRPS

**Comment by ran-codes** [comment]
## load_dta_to_db()

- use a high RAM >16GB at least becaues its just reading in .dta into memory then writing out as parquet. 
- you need to install stata package( i updated in .Rprofile) but run this once `renv::install('readstata13')`
- I added an argument ` subset = T` that just tests the function (loads the first dataset only) 
- feel free to play around with subseting within the function itself. 


## Issue 29

in #29, not sure. i edited the issue. but steps 2/3 where kind of the same step which is just this whole ETL process.

**Comment by ran-codes** [comment]
delete! moved this to dbt repo!

**Comment by her43** [comment]
@ran-codes I think we can close this issue, right?

**Comment by ran-codes** [comment]
@her43 Yup. ready to close.

Btw ... i just want to say you've been doing great with the ETL and DBT stuff and feel like you have a great grasp of this project so feel free to close/open issues as you see fit. 🍰
